
apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: DSSP-TargetP-11-qa
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/BackstageSSPPoC/k8s-manifests.git
    targetRevision: main
    path: apps/DSSP-TargetP-11/qa

  destination:
    server: https://kubernetes.default.svc
    namespace: qa

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
