
apiVersion: apps/v1
kind: Deployment
metadata:
  name: DSSP-TargetP-11
  namespace: default

spec:
  replicas: 1

  selector:
    matchLabels:
      app: DSSP-TargetP-11

  template:
    metadata:
      labels:
        app: DSSP-TargetP-11

    spec:
      containers:
        - name: DSSP-TargetP-11
          image: chaitanyapandeygspann/DSSP-TargetP-11:latest

          ports:
            - containerPort: 5000

          env:
            - name: PORT
              value: "5000"
